### ISSUE TITLE
More discussion on the beach-goer impact?

### ISSUE THREAD

**Issue by kbrose** [Chicago/predicting-e-coli-concentrations#10]
The validation section is a convincing argument that the now-cast model has equal or better performance to the previous model. But I feel like it may even be _underselling_ the actual impact of the model by providing detailed discussions and charts/tables for the _prediction_ performance, but only one paragraph for the performance of the model including the five (perfectly "predicted") feature beaches. (And I don't think I've ever before said a paper has undersold its findings, so that's new for me)

This could be particularly beneficial because the addition of a good chunk of True Negatives (and no False Positives) may bring the actual beach-goer's FPR closer to the target 1.8% with a beach-goer's TPR of a whopping ~56% by my calculations. To me, the ability to get true samples for a (bad behaving) subset of beaches was one of the biggest selling points of this method.

Thoughts?

**Comment by tomschenkjr** [comment]
@kbrose - I've added some text in the [discussion](https://github.com/Chicago/predicting-e-coli-concentrations/blob/master/predicting-e-coli-concentrations.Rmd#discussion) to touch on this point. Let me know if you think it could be expanded.

**Comment by kbrose** [comment]
Looks good, thanks @tomschenkjr
