### ISSUE TITLE
Embed code to generate figures and calculations

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#11]
It's time to connect the scripts from clear-water to the graphs, tables, and calculations in the paper. 

We should make use of the code already available in clear-water. However, we may need to write additional functions in the predicting-e-coli-concentrations, which can be specific to this repo.

Replace calculations showing improvements (e.g., number of days with warnings, accuracy/specificity/etc.) with the code that generates it. Likewise, any table or graph certainly should be generated from code.

ggplot graphs are very noisy, which is not ideal for journal submissions. We should use [another theme](https://rpubs.com/Koundy/71792) for suited for publication or [a light or minimal ggplot them](http://ggplot2.tidyverse.org/reference/ggtheme.html).

Right now, don't replace any code in the abstract section. There are some complications there and not sure how to tackle that, yet.

Because it's a significant coding effort, let's do all of this work in the respective issue branch.

## Incorporating clear-water repo

There are a couple of ways to incorporate code in git: [`submodule`](https://www.atlassian.com/blog/git/git-submodules-workflows-tips?_ga=2.115296327.1386987451.1512574911-1448399592.1512574911) and [`subtree`](https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree). That is, these functions will allow us to pull-in code from the clear-water project so it can be sourced.

Read-up on these, but I recommend the submodule approach. Namely, submodules will reference a specific commit. clear-water is an active project that may change in the future, but this paper is about the project at a [specific commit](https://github.com/Chicago/clear-water/tree/455e85cb2e63bed3d919961992561ca6c1a6a3f3). So, a submodule will let us generate the paper only using code from this commit, but allows clear-water to freely change.

## Code organization

We don't have a great practice for code organization in knitr. Generally, I recommend sourcing the necessary code from clear-water near the top of the document to prepare for it.

Then, add any other necessary code near the sections that need it. Please name code chunks as it's useful when debugging and more friendly for others.

Before adding code, make sure you can run the knitr document to create a PDF. This ensures you have the necessary packages before complicating it with R code (and will make debugging easier).

**Comment by nicklucius** [comment]
Thanks for all the information. After reading up, yeah I also prefer the submodule approach. I'll start to get things organized and code up the tables and graphs.

**Comment by nicklucius** [comment]
I've got the clear-water repo prepped so that the latest commit in `dev` is the one that I want to use for the submodule. And I also have the submodule snapshot in the `issue11` branch of this repo. I am able to generate the PDF and things look like they're working for the correlation heatmap, so I'll continue down the line with the other tables and graphs.

**Comment by tomschenkjr** [comment]
Looking at branch `issue11`, I attempt to run the PDF code but on page 3 comes out as

```
## We recommend that you use the dev version of ggplot2 with `ggplotly()`
## Install it with: `devtools::install_github('hadley/ggplot2')`
## We recommend that you use the dev version of ggplot2 with `ggplotly()`
## Install it with: `devtools::install_github('hadley/ggplot2')`
## We recommend that you use the dev version of ggplot2 with `ggplotly()`
## Install it with: `devtools::install_github('hadley/ggplot2')`
```

[Here is the PDF](https://github.com/Chicago/predicting-e-coli-concentrations/files/1548474/predicting-e-coli-concentrations.pdf)

**Comment by nicklucius** [comment]
OK, I think I fixed that. Could pull down the latest commit and try again? The correlation plot should be there now, and the warning messages should not pop up.

**Comment by tomschenkjr** [comment]
Yep, works on my end.

**Comment by tomschenkjr** [comment]
Great job on this. Closing.
