### ISSUE TITLE
Random Forest Tree Visualization

### ISSUE THREAD

**Issue by nicklucius** [Chicago/predicting-e-coli-concentrations#12]
While working on #11 I found a visual that I worked on but abandoned. It's a way to visualize a simplified version of one single tree of the random forest. For interpretation of the model, it's really not of much use since it's just a truncated version of one of the trees that gets a vote. But it might be interesting for explanation of how a random forest model works. I'll post it here just in case it's useful:

<img width="1233" alt="rf" src="https://user-images.githubusercontent.com/16853555/33776350-adc13c9c-dc06-11e7-9367-17985052c53e.png">

**Comment by tomschenkjr** [comment]
For now, I have some hesitations on using a single tree in the paper since it may be confused for the "final model". May be useful depending on editor feedback, but closing for now.
