### ISSUE TITLE
Chicago Prior-day model historical TPR/FPR

### ISSUE THREAD

**Issue by nicklucius** [Chicago/predicting-e-coli-concentrations#13]
There's something that I think we should note when talking about the historical performance of the Chicago Prior-day model (aka USGS). When the hybrid model pilot results are compared to the prior-day model, we compare apples with apples: since the hybrid model predicts a subset of beaches, its performance is measured up against the prior-day model performance on the same subset of beaches.

However, when we talk about the Chicago prior-day model generally in section 2, the TPR and FPR listed (3% and 4%) are for that same subset of beaches, not for all beaches. It seems like the data for all beaches should be discussed here. Using the data in the clear-water submodule, I calculated TPR for the prior-day model at 7% for 2015 and 11.9% for 2016, using all beaches.

At the beginning of the paper, it makes sense to talk about the general model performance across all beaches, and later on it make sense to talk about the apples-to-apples comparison. But it seems like there will to be an explanatory sentence about why the prior-day model performance in Section 2 differs from the Pilot results section.

**Comment by tomschenkjr** [comment]
Yes, this is a good point.

**Comment by tomschenkjr** [comment]
@nicklucius - can you incorporate this into the narrative? I'll be pushing some of my final changes today.
