### ISSUE TITLE
Get addresses for all co-authors

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#15]
In preparing the paper for submission, the journal will require us to list the physical/street addresses for all co-authors "where the work was completed" (not where they presently are). 

The @chihacknight co-authors can use the Chi Hack Night street addresses since the work was completed there.

For @tomschenkjr, @nicklucius, and @CallinOsborn, we should use the DoIT physical address.

Finally, will need the physical address (a school address is fine) for @rchesak.

**Comment by rchesak** [comment]
You can use the following address for me:
DePaul University - College of Computing and Digital Media 
243 S Wabash Ave, 
Chicago, IL 60604
