### ISSUE TITLE
Need 4 potential referees

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#16]
Journal will require us to submit 4 potential referees with name and address. I'm unsure if they need street address or email is fine.

**Comment by tomschenkjr** [comment]
As a first step, I'll reach out to Nevers at EPA to see if she is interested and whether there are others.

@nicklucius - any potential reviews that you met at State of Lake Michigan conference?

**Comment by nicklucius** [comment]
Sam Dorevitch at UIC comes to mind, and I believe he is a co-author on papers with Cathy Breitenbach regarding qPCR. We talked at SOLM and he was quite interested in the model.

I also talked to John Walthen, a Senior Science Advisor at the EPA, who works with beaches. He's interested in the model and I shared a draft paper with him.
