### ISSUE TITLE
Price differential for qPCR testing

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#2]
Previously, I've noted (see Chicago/clear-water#95) that qPCR testing is 5x more. But I think @ThorSean  noted it was 2x more expensive. I believe he pulled that from an article in the _Trib_, but I can't find it.

Sean, does this sound familiar?

**Comment by nicklucius** [comment]
I think it might come from this article: https://www.scientificamerican.com/article/dna-tests-offer-quicker-results-for-beach-bacteria/

This line is in the article: "Nevers estimated the new tests would cost about twice as much as the old ones."

This is from 2013, so it might be outdated.
