### ISSUE TITLE
Dotted line for Figure 3

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#22]
"Figure 3: "Receiver Operating Characteristic (ROC) for Hybrid Model and Prior-day Model" uses two color lines, but are not distinguishable when printed in grayscale. Need to move to a dotted line for one component of data or adjust line thickness.

**Comment by tomschenkjr** [comment]
I switched the graph style, but now get a different sort of problem where "linetype" is now printed in the graph. Might be an issue with the minimalist template. 

![image](https://user-images.githubusercontent.com/1639121/34754410-279080e2-f583-11e7-9afc-e753956e5d68.png)

@nicklucius - can you take a deeper look at this? Just need to generate the document and look at the PDF.

**Comment by nicklucius** [comment]
Sure, I had this issue originally too. I will commit the fix.
