### ISSUE TITLE
Create Title Page

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#26]
I think we need to submit a _separate_ file called the "Title Page". Below is the information to be included in that file:

> Title. Concise and informative. Titles are often used in information-retrieval systems. Avoid abbreviations and formulae where possible.
>
> Author names and affiliations. Please clearly indicate the given name(s) and family name(s) of each author and check that all names are accurately spelled. You can add your name between parentheses in your own script behind the English transliteration. Present the authors' affiliation addresses (where the actual work was done) below the names. Indicate all affiliations with a lower-case superscript letter immediately after the author's name and in front of the appropriate address. Provide the full postal address of each affiliation, including the country name and, if available, the e-mail address of each author.
>
> Corresponding author. Clearly indicate who will handle correspondence at all stages of refereeing and publication, also post-publication. This responsibility includes answering any future queries about Methodology and Materials. Ensure that the e-mail address is given and that contact details are kept up to date by the corresponding author.
>
> Present/permanent address. If an author has moved since the work described in the article was done, or was visiting at the time, a 'Present address' (or 'Permanent address') may be indicated as a footnote to that author's name. The address at which the author actually did the work must be retained as the main, affiliation address. Superscript Arabic numerals are used for such footnotes.

**Comment by tomschenkjr** [comment]
@nicklucius - can you add the email addresses for each co-author? Just look at the `.Rmd` file and add an `email` field under the `author` field in the top YAML section. You can see how I did it for you and me, but I don't have all the email addresses on hand.

**Comment by nicklucius** [comment]
Sure thing. I've sent out messages to people who I contacted outside email to get their email addresses.
