### ISSUE TITLE
Confusion matrix for 2017 results

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#3]
On the Clear Water wiki there are [results for the 2017 summer pilot](https://github.com/Chicago/clear-water/wiki/2017-Results).  Can you include the full confusion matrix?

**Comment by tomschenkjr** [comment]
Also, can you provide specificity, sensitivity, and overall proportion of correct decisions for the 2017 pilot?

**Comment by nicklucius** [comment]
Sure thing, I've added the full results to the wiki: https://github.com/Chicago/clear-water/wiki/2017-Results
