### ISSUE TITLE
Historical true-positive and false-positive rates

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#4]
I think I saw on your desk a handwritten table of true-positive and false-positive rates for the USGS model. Can you provide those here?

**Comment by nicklucius** [comment]
I've added the historical rates for the USGS model on the wiki [here](https://github.com/Chicago/clear-water/wiki/2017-Results). It was only deployed for those two years (2015 and 2016) that we have data for.

Also on that notepad I had the full results of validation for each year of the new model (2006 through 2016), to help determine the best threshold to use for model decisions. I have that all in a spreadsheet now, and here are the details. This is for the model with the ideal beach selections discussed in the methodology section.

Year | Threshold @ 1.5 FPR
-- | --
2006 | 443
2007 | 504
2008 | 453
2009 | 292
2010 | 450
2011 | 337
2012 | 326
2013 | 292
2014 | 392
2015 | 327
**Avg** | **381.6**
SD | 72.6


Year | TPR @ 381 Threshold | FPR @ 381 Threshold
-- | -- | --
2006 | 0.545 | 0.019
2007 | 0.25 | 0.032
2008 | 0.125 | 0.026
2009 | 0.051 | 0.0015
2010 | 0.203 | 0.0205
2011 | 0.218 | 0.008
2012 | 0.355 | 0.009
2013 | 0.451 | 0.005
2014 | 0.283 | 0.015
2015 | 0.193 | 0.011
Avg | 0.2674 | 0.0147
SD | 0.141 | 0.009
**Final Holdout 2016** | **0.216** | **0.015**
