### ISSUE TITLE
Remarks on figures and tables

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#54]
- [x] A map of the beach locations would be helpful
- [x] Title missing for Figure 1
- [x] Table 2- would be improved if the authors also included a list of the attributes included in each of these models as well as what the ROC values were for these models. Typically and ROC >0.7 is considered a "good" performing model
- [x] **An additional table in a similar format as Table 2 showing the results from different models tried, along with the included attributes and corresponding ROC values would also help the reader understand the impact of the other environmental variables.

**Comment by nicklucius** [comment]
Will add a map and title for Figure 1. For Table 2, we can add some language in line 213 to explain what attributes were used.

For ROC values, calculate ROC values for the models and add to Table 2. This is similar to #61.

The request for an additional table is similar to #47 and #52.

**Comment by nicklucius** [comment]
Here is a first pass at a map. 
![image](https://user-images.githubusercontent.com/16853555/39890780-7b8b8498-5461-11e8-8b50-fcd4bfe8d939.png)

**Comment by tomschenkjr** [comment]
Will you be able label with beach names? Everything else looks good.

_
Tom Schenk Jr.
Chief Data Officer
Department of Innovation and Technology
City of Chicago
(312) 744-2770
tom.schenk@cityofchicago.org | @ChicagoCDO
data.cityofchicago.org | opengrid.io | digital.cityofchicago.org | chicago.github.io | dev.cityofchicago.org


________________________________

**Comment by nicklucius** [comment]
@tomschenkjr I can think of a few different ways to do it. My first thought is to put labels right next to each beach, and for the North cluster of beaches, alternate left/right and/or space them out. Let me know if you think of other ideas to try out. I'll play around with it and repost.

**Comment by tomschenkjr** [comment]
Yeah, no particular idea, just whatever works for the display.

_
Tom Schenk Jr.
Chief Data Officer
Department of Innovation and Technology
City of Chicago
(312) 744-2770
tom.schenk@cityofchicago.org | @ChicagoCDO
data.cityofchicago.org | opengrid.io | digital.cityofchicago.org | chicago.github.io | dev.cityofchicago.org


________________________________

**Comment by nicklucius** [comment]
Beach labels added.
![image](https://user-images.githubusercontent.com/16853555/39947199-9fa54654-5536-11e8-85cd-12e509b397b2.png)

**Comment by tomschenkjr** [comment]
Awesome!


Tom Schenk Jr.

Chief Data Officer

Department of Innovation and Technology

City of Chicago

(312) 744-2770

tom.schenk@cityofchicago.org

data.cityofchicago.org<https://data.cityofchicago.org> | opengrid.io<http://www.opengrid.io/> | digital.cityofchicago.org<http://digital.cityofchicago.org> | chicago.github.io<https://chicago.github.io> | dev.cityofchicago.org<http://dev.cityofchicago.org>

________________________________

**Comment by tomschenkjr** [comment]
Did this code get committed? I see it's on `issue54` branch, but no pull request yet?

**Comment by nicklucius** [comment]
You're right--It is committed to the `issue54` branch but there's is no pull request--I'll add one now.

**Comment by tomschenkjr** [comment]
Looks like everything is done, so am closing.
