### ISSUE TITLE
Overall remarks from Reviewer 1

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#55]
> Overall the paper is clear and well written and presents an interesting "real world" application of a predictive model to help predict beach closures using FIB data.
However, there are details of the modeling approach that need to be further elaborated on such as what attributes were included in the different models and why certain attributes were removed. The authors need to present data from all the various models tried with the corresponding attributes and model performances  (even if in supplementary contents). Also, the discussion section is significantly lacking in terms of placing this current research in the context of other global research and how the findings of this paper relate to existing work that has been done and how this model compares to other predictive models. There are no references in the discussion section. Also- see detailed comments below.

**Comment by nicklucius** [comment]
These overall remarks are further elaborated by #47 and #53, so marking this as duplicate.
