### ISSUE TITLE
Correlation between beaches

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#6]
Can you pull together some tables showing the correlation between beaches? I think the editors will be asking us for that.

**Comment by nicklucius** [comment]
Here are a few tables and a plot. The tables show the correlation coefficient for each beach against each other. This is for the log of E. coli culture test results. The plot might be too much, but I think it's interesting because you can clearly see which beaches are correlated and which are not. Let me know if it'd be helpful to have these in another format.

![cortable1](https://user-images.githubusercontent.com/16853555/32969725-cea6fac0-cbab-11e7-83a1-480700140258.PNG)
![cortable2](https://user-images.githubusercontent.com/16853555/32969735-d382572e-cbab-11e7-8fe6-92711583dcf2.PNG)
![corplot](https://user-images.githubusercontent.com/16853555/32969739-d5d0b1e2-cbab-11e7-8138-5b45917e073e.PNG)

**Comment by tomschenkjr** [comment]
Thanks. It's a difficult challenge to communicate because of the large array of data. But, for the paper, lets see if we can find an interesting way to visualize this. [Correlation heatmap](http://www.sthda.com/english/wiki/ggplot2-quick-correlation-matrix-heatmap-r-software-and-data-visualization) comes to mind (that's just the first link I found) or could even do forced network diagram (though likely overly complicated), or some other method.

See if you can try another visualization that you think is workable.

**Comment by nicklucius** [comment]
I put the R code for the paper plots on the clear-water [dev branch](https://github.com/Chicago/clear-water/tree/dev/Research_Paper) and rendered an HTML file of the correlation heat map, which you can see here:

https://rawgit.com/Chicago/clear-water/dev/Research_Paper/beach-correlation-heatmap.html

**Comment by tomschenkjr** [comment]
Looks great. Can you also write a paragraph or two on the differences you see in the native correlation clustering (the plot) versus the clustering we see with the multivariate K-means.

Choose the level of clusters at your discretion to describe the differences. I can work it into the narrative.

**Comment by nicklucius** [comment]
Sure thing. One difference is that in the native heirarchical clustering, North Avenue and Oak Street are quite removed from each other and do not meet in the hierarchy at any split. However, in K-means, not only are they are in the same cluster, but they are the only beaches in their cluster. Also, South Shore in 57th are are a bit removed in the hierarchical clustering, but also have their own k-means cluster to themselves. These seem to both be explained by proximity. 

There are similarities too. The North side beaches that ended up in the same k-means clusters are identical in the hierarchical cluster if you step back 2 levels. Also, at the most general level that splits the beaches into 2 groups, the groups are very close to a perfect North/South split at around Oak Street with the exception of 12th, 31st, and Montrose. 

Here is a link to the clusters: https://github.com/Chicago/predicting-e-coli-concentrations/blob/master/predicting-e-coli-concentrations.Rmd#identifying-beach-clusters

**Comment by tomschenkjr** [comment]
Can you place the image file of the correlation heatmap and replace [the scatterplot graph](https://github.com/Chicago/predicting-e-coli-concentrations/blob/master/predicting-e-coli-concentrations.Rmd#hybrid-nowcast-model)?

**Comment by nicklucius** [comment]
This should be completed by https://github.com/Chicago/predicting-e-coli-concentrations/commit/bb2966e59dbb8d711b1d27bafc3b495ce64f1824.
