### ISSUE TITLE
Examine model fit

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#62]
> Methods/Results? Is there any way to examine model fit (for example, are the model predicted outcomes not significantly different than the actual observed outcomes?. Accuracy is reported, however, this is somewhat different. how well do the model predicted values

**Comment by nicklucius** [comment]
With Monte-Carlo simulation of p-value, the [degrees of freedom were not used](https://stats.stackexchange.com/questions/291540/why-are-the-degrees-freedom-not-available-when-i-conduct-a-monte-carlo-simulatio). I'll give the calculations with and without Monte-Carlo simulation.

### Without Monte-Carlo p-value simulation

This error is reported by R:

```
Warning message:
In chisq.test(ct2015usgs, simulate.p.value = FALSE) :
  Chi-squared approximation may be incorrect
```

Model                   | Chi-square test statistic | Degrees of Freedom | p-value
--------------------|---------------------------|------------------------|------------|
Hybrid Pilot 2017 | 23.012                            | 1                                | 1.61e-06   |
Prior Day 2016     | 0.88035                          | 1                                | 0.3481       |
Prior Day 2015     | 0.50704                          | 1                                | 0.4764      |

### With Monte-Carlo p-value simulation

To make sure we get reproducible values here, we should set a seed if we keep the Monte-Carlo simulation.

Model                   | Chi-square test statistic | Degrees of Freedom | p-value
--------------------|---------------------------|------------------------|------------|
Hybrid Pilot 2017 | 26.107                            | NA                             | 0.0004998|
Prior Day 2016     | 2.3922                            | NA                             | 0.1614      |
Prior Day 2015     | 1.2687                            | NA                             | 0.3988      |

Also, here are the contingency tables used to generate the Chi-square test statistic for each model:

### Hybrid Pilot 2017

**E. Coli Level**           | Actual Normal | Actual Exceedance
-------------------------|-----------------|---------------------
Predicted Normal         | 1421                 | 91
Predicted Exceedance  | 32                     | 11

### Prior Day 2016

**E. Coli Level**           | Actual Normal | Actual Exceedance
-------------------------|-----------------|---------------------
Predicted Normal         | 825                 | 52
Predicted Exceedance  | 10                    | 2

### Prior Day 2015

**E. Coli Level**           | Actual Normal | Actual Exceedance
-------------------------|-----------------|---------------------
Predicted Normal         | 866                 | 91
Predicted Exceedance  | 14                   | 3

**Comment by nicklucius** [comment]
@tomschenkjr - heads up that I just edited the 2017 Pilot model numbers (it had pulled in some 2018 results when I ran these, so I updated after removing them).

**Comment by tomschenkjr** [comment]
@nicklucius - thanks for showing the contingency tables. It helped me flag that we cannot use Chi-square because it [violates a rule on any cell size being below 5](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3900058/), so it's not a great test.

Let's switch to a [Matthew's correlation coefficient](https://en.wikipedia.org/wiki/Matthews_correlation_coefficient), which can be done using the confusion matrix and is bound between -1 and 1. Based on my hand calculation, 2017 Hybrid is +.14, 2016 is 0.05, and 2015 is 0.04.

Please code this and insert it in place of the p-values. You can use the package, but probably easier to hand-code this--either way.
