### ISSUE TITLE
Legend for figure 1

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#65]
> Figure 1 (I presume), needs a description underneath and a scale name for what I presume are correlation coefficients (Pearson or Spearman or some other coefficient?)

**Comment by nicklucius** [comment]
Simliar to #54

**Comment by tomschenkjr** [comment]
Tested this branch on my computer and I see the caption:

![image](https://user-images.githubusercontent.com/1639121/39202457-933ba14c-47b7-11e8-939e-76af32838898.png)
