### ISSUE TITLE
Review 2 general notes

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#66]
> Overall, the presented manuscript demonstrates a significant enhancement in the beach water quality modeling community using molecular data to inform forecasting. Accordingly, this study is novel. Like previous models, using non-molecular data, the sensitivity is still relatively weak; however, it is still an improvement. The paper demonstrates the potential for modeling of beach water quality conditions for swimming advisories; however, it also accurately describes the dilemmas associated with current models. Another positive hallmark of the paper is that it uses a machine learning-based modeling technique that is also innovative in the area of beach forecasting when new molecular data are added. Overall, the paper does appear to be statistically sound; however, the paper could present some additional post-model diagnostics if available (notably, goodness-of-fit tests). In regards to discussion-related material, the paper could also better describe where it fits (or where the results/methods fit) in the context of the current national recreational water quality criteria. Lastly, speaking to the public health significance of this work would also add value if possible. Overall, the paper is fairly well done, minor tweaks in organization could be done, and some minor improvement in grammar (tense) and flow are possible to ease readability.

**Comment by nicklucius** [comment]
For goodness of fit, use a Chi-square test.

@tomschenkjr will take a general look at discussion and review of literature.

**Comment by nicklucius** [comment]
Goodness of fit work is being done under #62
