### ISSUE TITLE
Inform editor of delayed resubmission

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#68]
The Editor requested that revisions be submitted within a month of feedback, so due approximately by May 5th. This is unlikely as we sort-out our reply and make requisite edits. 

Nevertheless, we should communicate with the Editor to inform them of our timeline for resubmission, ensuring that it is OK with them. We should provide an estimated timeline.

I'm thinking 2 months, so, attempt to resubmit by June 5th.

Thoughts?

**Comment by nicklucius** [comment]
I sent the request for extended deadline to 6/8 (1 month from original deadline of 6/8) today.

**Comment by nicklucius** [comment]
The Editor has extended the due date to 6/8.
