### ISSUE TITLE
Include description of RF model in paper

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#8]
Right now, the paper does not fully explain the model created by the Random Forest that was used in the paper. While we describe the inputs, we hardly describe the model output.

  - [ ] Create a graph (and supporting table) of the variable importance
  - [ ] Write a 3-4 paragraph narrative explaining major findings of the model itself (most important features, relative comparison of importance, fit, etc.)

**Comment by nicklucius** [comment]
I added plots and tables along with the narrative. Some of the plots are native to the `randomForest` package so they do not match the aesthetic of the `ggplot` for the ROC. Depending on what we keep, I can get to the `randomForest` internals to make some better looking plots.

**Comment by tomschenkjr** [comment]
Thanks.

Thanks OK on the aesthetic mistmatch. Because of the journal process, we probably eventually want to move to a more basic graph style.
