### ISSUE TITLE
Figure numbers

### ISSUE THREAD

**Issue by nicklucius** [Chicago/predicting-e-coli-concentrations#80]
Figures are referred to in text as 1, 2, 3 etc., but are really labeled A.1, A.2, A.3, and so on.

**Comment by tomschenkjr** [comment]
Yeah, that will get corrected when they prepare for publication. We can keep Figure 1, 2, etc. Just need to make sure there is a correspondence, i.e., 1 = A.1

_
Tom Schenk Jr.
Chief Data Officer
Department of Innovation and Technology
City of Chicago
(312) 744-2770
tom.schenk@cityofchicago.org | @ChicagoCDO
data.cityofchicago.org | opengrid.io | digital.cityofchicago.org | chicago.github.io | dev.cityofchicago.org


________________________________

**Comment by nicklucius** [comment]
OK got it, thanks. Closing.
