### ISSUE TITLE
Confusion matrix not showing up

### ISSUE THREAD

**Issue by nicklucius** [Chicago/predicting-e-coli-concentrations#81]
At the end of the supplementary materials, there is code for a confusion matrix, but it is not showing up in the paper.

@tomschenkjr - I've tried to fix this, but have not figured it out yet.

**Comment by tomschenkjr** [comment]
What's the confusion matrix for? The alternate model?

**Comment by nicklucius** [comment]
It's for the main hybrid model. I think it could be scrapped in light of the rest of the evaluation (ROC, AUC, etc).

**Comment by nicklucius** [comment]
Also, I think it's been there for a long time and maybe an artifact of an early draft.

**Comment by tomschenkjr** [comment]
I agree, we can skip this.
