### ISSUE TITLE
Resubmit revisions to editor

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#88]
As we wrap-up revisions, beginning a list of a final checklist of items. Discuss remaining items in this thread. We can assign specific responsibilities as we go along.

  - [x] Confirm no other pull requests or changes are needed
  - [x] Open pull request against `master` branch
  - [x] Confirm paper generates correctly on `master` branch
  - [x] Double-check [open issues](https://github.com/Chicago/predicting-e-coli-concentrations/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Revision+1%22), confirm no remaining issues exist.
  - [x] Create a new [release](https://github.com/Chicago/predicting-e-coli-concentrations/releases)
  - [x] Review [letter to editor](https://github.com/Chicago/predicting-e-coli-concentrations/wiki/Letter-to-Editor-for-Revision) to submit alongside revisions. Edit as necessary. Include language for #51.
  - [x] 🎉🎈🙌👏Submit revisions to _Water Research_ :shipit:  @nicklucius

**Comment by nicklucius** [comment]
I merged the PR and am able to generate the paper on the master branch. I'll double check open issues and close them as I confirm they were addressed.

**Comment by tomschenkjr** [comment]
@nicklucius - I've accepted #90 into `dev` and also opened a pull request against `master` (#91). Please confirm you want this on `master`.

Separately, I compared the tables using `master` branch from this repo and also the Clear-Water repo. Numbers are correctly generated.

I have not identified any other changes besides #91.

**Comment by nicklucius** [comment]
Reopening. It was inadvertantly autoclosed by #91.

**Comment by tomschenkjr** [comment]
@nicklucius - can you create a new release and attach the title page and main PDF to that release? If you look at prior releases, it had two PDFs:

  * The title page only contains the title page (with author names) but no other pages
  * The manuscript eliminates the title page, but all other pages are kept.

**Comment by nicklucius** [comment]
@tomschenkjr  - the release is done, now I just need to edit the letter and submit! I'll let you know once I add the letter language so you can check it out.

**Comment by nicklucius** [comment]
@tomschenkjr - In the resubmission process, I've noticed that the journal offers a feature to link to our data:

"In this section, you can make your research data available with your article. Sharing research data helps other researchers evaluate your findings, and increases trust in your article. Research data can include, (but is not limited to): raw data, processed data, software, algorithms, protocols, methods and materials. Please cite your research data within your article; consult your journal's Guide for Authors for instructions.
If your research data is already hosted in a repository, you can link it to your article here."

Also: 
https://www.elsevier.com/authors/author-services/research-data/data-base-linking

I could link both repositories, but each one needs a DOI. Plus, I noticed the clear-water DOI links to an old commit. I am wondering if we should add a DOI for this repo and also do a new release and update the DOI for the Clear Water repo. Thoughts?

**Comment by tomschenkjr** [comment]
Good idea. Probably makes most sense to link to Clear Water. Fortunately, to update the DOI for the Clear Water repository, just create a new release and a new DOI will be created.

**Comment by tomschenkjr** [comment]
Here is the DOI for the paper repository (separate from the bioRxiv and Clear Water repo): https://doi.org/10.5281/zenodo.1434260

Badge: [![DOI](https://zenodo.org/badge/101983999.svg)](https://zenodo.org/badge/latestdoi/101983999)

**Comment by nicklucius** [comment]
@tomschenkjr - excellent, thank you. I hope to have it submitted today.

**Comment by nicklucius** [comment]
@tomschenkjr - I'll give you the satisfaction of hitting close on this issue, since I got to click the submit button in Elsevier.
